#!/usr/bin/env sh

IMAGE_REPOSITORY="containerly/createrepo"
IMAGE_TAG="latest"

endPrintfWithStatus()
{
    if [ $1 -eq 0 ]; then
        printf "[OK]"
    else
        printf "[ERROR]"
    fi

    printf "\n"
}

IMAGE_STRING="${IMAGE_REPOSITORY}:${IMAGE_TAG}"
if [ "${1}" == "upgrade" ]; then
    original_id=$(docker images "${IMAGE_STRING}" -q)

    printf "Pulling ${IMAGE_STRING}... "
    docker pull "${IMAGE_STRING}" &> /dev/null
    endPrintfWithStatus $?

    if [ $? -eq 1 ]; then
        echo "There was an error pulling ${IMAGE_STRING}."
        echo "Try running `docker pull ${IMAGE_STRING}` manually to diagnose the error."
        exit 1
    fi

    new_id=$(docker images "${IMAGE_STRING}" -q)

    if [ ! -z "${original_id}" ] && [ "${new_id}" != "${original_id}" ]; then
        printf "Removing old image... "
        docker rmi "${original_id}" &> /dev/null
        endPrintfWithStatus $?
    else
        echo "You have the latest image for ${IMAGE_REPOSITORY}."
    fi

    exit
fi

tty=""
tty -s && tty=--tty


docker run \
    $tty \
    --rm \
    --interactive \
    --user $(id -u):$(id -g) \
    --volume $(pwd):/build \
    --workdir /build \
    "$IMAGE_REPOSITORY" $*
