#!/usr/bin/env sh

if command -v xrandr > /dev/null 2>&1; then
    mon=$(xrandr --query | grep " connected primary" | cut -d " " -f 1)
    MONITOR=$mon polybar --reload top &
else
    polybar --reload top &
fi
