#!/usr/bin/env zsh
#
# wo - "work on"
# This lets you quickly jump into a project directory.
#
# Usage:
#   wo <tab>


if [ -n "$1" ]; then
    if ! cd "${WOPATH}/${1}" > /dev/null 2>&1; then
        echo "wo: error: argument '${1}' not found"

        local -a matches
        matches=()
        for dir in "$WOPATH"/*; do
            if [ -d "${dir}/${1}" ]; then
                shortname=$(basename "$dir")
                matches=("${shortname}/${1}" "$matches")
            fi

        done

        if [ "${#matches}" -gt 0 ]; then
            echo "wo: info: we found the following alternative(s):"
            for match in $matches; do
                echo "  - $match"
            done
        fi
    fi
else
    cd "$WOPATH"
fi
