#!/usr/bin/env sh

ROOT=$(git rev-parse --show-toplevel)
if [ -z "$ROOT" ]; then
    echo "FAIL    Unable to determine root repository directory."
    exit 1
fi


SOURCE="${ROOT}/rcrc"
DESTINATION="${HOME}/.rcrc"
if [ ! -f "$DESTINATION" ] && [ -f "$SOURCE" ]; then
    if command cp "$SOURCE" "$DESTINATION"; then
        echo "OKAY    Successfully installed the initial rcm configuration file"
    else
        echo "FAIL    Failed installing initial rcm configuration file"
        exit 1
    fi
fi
