#! /bin/sh

sxhkd &

# load polybar
polybar-launch
xset m 1/2 4

# bspc rules for bspwm
bspc config border_width        0
bspc config window_gap          0
bspc config top_padding         0
bspc config left_padding        0
bspc config right_padding       0
bspc config bottom_padding      0

bspc config split_ratio          	0.50
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config focus_by_distance    	false
bspc config history_aware_focus  	true
bspc config focus_follows_pointer 	true
bspc config pointer_follows_focus 	false
bspc config click_to_focus 			false
bspc config adaptive raise 			true

bspc config center_pseudo_tiled  true

bspc config normal_border_color "#526562"
bspc config focused_border_color "#47575f"
bspc config presel_feedback_color "#804f4e"

bspc monitor -d I II III IV

bspc rule -a Steam desktop=^3 follow=on split_dir=right
bspc rule -a URxvt:updates state=floating
bspc rule -a URxvt:pulsemixer state=floating
bspc rule -a URxvt:mutt desktop=^2 follow=on
bspc rule -a URxvt:weechat desktop=^2 follow=on
bspc rule -a Gimp desktop=^4 follow=on
bspc rule -a URxvt:vpn desktop=^5 follow=on state=floating
bspc rule -a URxvt:upass state=floating
