#! /bin/sh

/usr/lib/geoclue-2.0/demos/agent &
sxhkd &

# reconfigure monitors
xrandr --output eDP-1 --primary --mode 1920x1080 --rotate normal

# load polybar
$HOME/.local/bin/polybar-launch
xset m 1/2 4

# bspc rules for bspwm
bspc config border_width        0
bspc config window_gap          0
bspc config top_padding         0
bspc config left_padding        0
bspc config right_padding       0
bspc config bottom_padding      0

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     false
bspc config history_aware_focus   true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config click_to_focus        false
bspc config adaptive raise        true
bspc config center_pseudo_tiled   true

bspc config normal_border_color "#526562"
bspc config focused_border_color "#47575f"
bspc config presel_feedback_color "#804f4e"

# create desktops
bspc monitor eDP-1 -n main -d term web work canary photo
